included: # paths to include during linting. `--path` is ignored if present.
  - Nexd
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
line_length: 180
function_body_length:
  - 100
  - 150
function_parameter_count:
  - 8
  - 15
